#ifndef PIUIO_EMU_H
#define PIUIO_EMU_H

#define PIULXIO_STR_MANUFACTURER	u"ANDAMIRO"
#define PIULXIO_STR_PRODUCT		u"PIU HID V1.00"
#define PIULXIO_CTRL_300  {0x0409, 0}

#define PIULXIO_VENDOR_ID 0x0d2f
#define PIULXIO_PRODUCT_ID 0x1020
#define PIULXIO_ENDPOINT_OUT 0x02
#define PIULXIO_ENDPOINT_IN 0x01
#define PIULXIO_ENDPOINT_PACKET_SIZE 0x10
#define PIULXIO_DESC_MAX_PACKET_SIZE 0x10

#define USB_DIR_OUT 0x40
#define USB_DIR_IN 0x80
#define PIULXIO_GET_DESCRIPTOR 0x6
#define PIULXIO_HID_SET_REPORT 0x9

// Legacy ones 
#define PIUIO_VENDOR_ID 0x0547
#define PIUIO_PRODUCT_ID 0x1002

#define PIUIOBUTTON_VENDOR_ID 0x0D2F
#define PIUIOBUTTON_PRODUCT_ID 0x1010

#define PIUIO_CTL_REQ 0xAE

#define USB_TYPE_STANDARD (0x00 << 5)
#define USB_TYPE_CLASS (0x01 << 5)
#define USB_TYPE_VENDOR (0x02 << 5)
#define USB_TYPE_RESERVED (0x03 << 5)

#define USB_RECIP_DEVICE 0x00
#define USB_RECIP_INTERFACE 0x01
#define USB_RECIP_ENDPOINT 0x02
#define USB_RECIP_OTHER 0x03

#define PIUIO_ENDPOINT_OUT 0x02
#define PIUIO_ENDPOINT_IN 0x06
#define PIUIO_ENDPOINT_PACKET_SIZE 0x200

#define PIUIOBUTTON_ENDPOINT_OUT 0x02
#define PIUIOBUTTON_ENDPOINT_IN 0x01

extern unsigned char bytes_l[4];
extern unsigned char bytes_f[16];
extern int piuioemu_mode;

#define WITH_PIULXIO 0x1
#define WITH_PIUIO 0x2
#define WITH_PIUIOBUTTON 0x4
#define EMU_PIUIO_BUTTON 0x8

#ifdef DEBUG
#define PRINTF(fmt, ...) printf(fmt, ## __VA_ARGS__)
#else
#define PRINTF(fmt, ...)
#endif

#endif // PIUIO_EMU_H
